repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.8.0
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort